# Generated by Django 2.2.6 on 2021-01-20 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210120_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipefakeingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipefakeingredient',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='RecipeFakeIngredient',
        ),
    ]
